from unittest.mock import patch

import pytest

from app.infrastructure.scrapers.playwright_scraper import PlaywrightScraper
from app.interfaces.api.schemas.ingest import IngestResponse


@pytest.mark.asyncio
async def test_playwright_scraper_basic_scrape():
    """정상적인 URL에 대해 Playwright가 마크다운을 반환하는지 테스트"""
    scraper = PlaywrightScraper()
    url = "https://example.com"

    # 실제 네트워크 요청 없이 인터페이스만 테스트하기 위해
    # 내부 Playwright 동작을 모킹하거나,
    # 테스트용 로컬 HTML 파일을 사용할 수 있음.
    # 여기서는 TDD Warming up을 위해 인터페이스 호출 성공을 검증.

    with patch.object(
        PlaywrightScraper,
        "scrape",
        return_value=IngestResponse(url=url, markdown="# Test Content", metadata={"title": "Test"}),
    ):
        result = await scraper.scrape(url)
        assert str(result.url).rstrip("/") == url.rstrip("/")
        assert "# Test Content" in result.markdown
        assert result.metadata["title"] == "Test"


@pytest.mark.asyncio
async def test_playwright_scraper_dynamic_content():
    """JS가 실행되어야 나타나는 콘텐츠를 긁어오는지 테스트 (Mock)"""
    scraper = PlaywrightScraper()
    url = "https://dynamic-site.com"

    # 렌더링 결과에 특정 JS 생성 텍스트가 포함되어야 함
    expected_text = "Generated by JS"

    with patch.object(
        PlaywrightScraper,
        "scrape",
        return_value=IngestResponse(url=url, markdown=f"This is {expected_text}", metadata={"title": "Dynamic"}),
    ):
        result = await scraper.scrape(url)
        assert expected_text in result.markdown


@pytest.mark.asyncio
async def test_playwright_scraper_error_handling():
    """잘못된 URL이나 타임아웃 발생 시 적절히 예외가 발생하는지 테스트"""
    scraper = PlaywrightScraper()
    url = "https://invalid-url-site.com"

    with patch.object(PlaywrightScraper, "scrape", side_effect=Exception("Timeout")):
        with pytest.raises(Exception) as excinfo:
            await scraper.scrape(url)
        assert "Timeout" in str(excinfo.value)
